name             'devbox'
maintainer       'Christopher Deutsch'
maintainer_email 'chef@ispeakdeutsch.com'
license          'BSD'
description      'Installs/Configures a devbox'
long_description 'Installs/Configures a devbox'
version          '0.1.0'

depends 'ruby_rbenv'
depends 'ruby_build'
depends 'apt'
